version: "3"

services:
  db:
    image: "postgres:latest"
    container_name: db
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: october 
      
    volumes:
      - ./postgres_db_data/:/var/lib/postgresql/data/